### ISSUE TITLE
Feat: Button exec action to close WlxOverlay

### ISSUE THREAD

**Issue by PassiveLemon** [galister/wlx-overlay-s#61]
As far as I know, there is no way to close WlxOverlay from within the program.
Tried to use a command on a button:
```
- type: Button
    rect: [200, 0, 80, 45]
    font_size: 20
    bg_color: "#f05d6b"
    fg_color: "#222222"
    text: "Exit"
    click_down:
      - type: Exec
        command: [ "kill", "$(pgrep wlx-overlay-s)" ]
      - type: Toast
        message: "Killing WlxOverlay"
```
But `$(pgrep wlx-overlay-s)` is taken literally and not evaluated into the PID.

Reasoning:
When using WiVRn with WlxOverlay as the default application, there is no way to fully leave the VR session without killing WlxOverlay from the computer, which is inconvenient.
